
services:
  mysql:
    image: mysql:8.0
    container_name: unsch-mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: mantenimiento_computo
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password_123
      MYSQL_ROOT_PASSWORD: root_password_123
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
